export const TableOfContentName = {
  Basic: 'basic',
  AsIcon: 'as-icon',
  WithNetworksList: 'with-networks-list',
  CustomConnectButton: 'custom-connect-button',
  CustomConnect: 'custom-connect',
  API: 'api',
  Customized: 'customized',
  CustomDialog: 'custom-dialog',
  W3sConnectWalletComponent: 'W3sConnectWalletComponent',
  W3sWalletConnectService: 'W3sWalletConnectService',
  W3sAccountButtonComponent: 'W3sAccountButtonComponent',
  W3sAccountBalanceComponent: 'W3sAccountBalanceComponent',
  W3sDialogService: 'W3sDialogService',
  W3sFaucetComponent: 'W3sFaucetComponent',
  W3sTableComponent: 'W3sTableComponent',
  W3sNetworkDropdownComponent: 'W3sNetworkDropdownComponent',
  W3sTransactionsHistoryComponent: 'W3sTransactionsHistoryComponent',
  W3sTransactionsListComponent: 'W3sTransactionsListComponent',
  W3sTransactionService: 'W3sTransactionService',
}
