import { AucDialogPosition } from './types';
import { AucCustomizeDialogOverlayConfigInterface } from './interfaces';

export class AucDialogConfig<D = any> {
  data?: D; // Data for injected component.
  width?: string; // '300px', '50%', '1rem' ...
  height?: string; // '300px', '50%', '1rem' ...
  minWidth?: string; // '300px', '50%', '1rem' ...
  minHeight?: string; // '300px', '50%', '1rem' ...
  maxWidth?: string; // '300px', '50%', '1rem' ...
  maxHeight?: string; // '300px', '50%', '1rem' ...
  position?: AucDialogPosition;
  dialogClass?: string | string[]; // Add custom class to the dialog container.
  panel?: {
    panelClass: string | string[]; // Add custom class to the dialog panel.
  };
  overlay?: AucCustomizeDialogOverlayConfigInterface; // customize overlay.
}
