import { APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS } from '../enums';
import { ApplicatureDialogPosition } from '../types';

export interface ApplicatureCustomizeDialogConfig {
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.WIDTH]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.HEIGHT]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.MIN_WIDTH]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.MIN_HEIGHT]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.MAX_WIDTH]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.MAX_HEIGHT]?: string;
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.CLASSES]?: string | string[];
  [APPLICATURE_CUSTOMIZE_DIALOG_CONFIG_KEYS.POSITION]?: ApplicatureDialogPosition;
}
