import { AUC_WRONG_NETWORK_APPEARANCE } from '../enums';

export type AucWrongNetworkAppearance = AUC_WRONG_NETWORK_APPEARANCE.DISCONNECT
  | AUC_WRONG_NETWORK_APPEARANCE.NONE
  | AUC_WRONG_NETWORK_APPEARANCE.SWITCH;
