import { AUC_CHAIN_ID } from '../renamed/enums';

export const AucChainName: { [key: string]: string } = {
  [AUC_CHAIN_ID.ARBITRUM_MAINNET]: 'Arbitrum Mainnet',
  [AUC_CHAIN_ID.ARBITRUM_TESTNET]: 'Arbitrum Rinkeby Testnet',
  [AUC_CHAIN_ID.ASTAR_MAINNET]: 'Astar Network Mainnet',
  [AUC_CHAIN_ID.ASTAR_TESTNET]: 'Shibuya Testnet',
  [AUC_CHAIN_ID.AVALANCH_MAINNET]: 'Avalanche Network Mainnet',
  [AUC_CHAIN_ID.AVALANCH_TESTNET]: 'Fuji Testnet',
  [AUC_CHAIN_ID.BSC_MAINNET]: 'Binance Smart Chain Mainnet',
  [AUC_CHAIN_ID.BSC_TESTNET]: 'Binance Smart Chain Testnet',
  [AUC_CHAIN_ID.ETHEREUM_MAINNET]: 'Ethereum Mainnet',
  [AUC_CHAIN_ID.FANTOM_MAINNET]: 'Fantom Opera',
  [AUC_CHAIN_ID.FANTOM_TESTNET]: 'Fantom Testnet',
  [AUC_CHAIN_ID.GOERLI_TESTNET]: 'Goreli Testnet',
  [AUC_CHAIN_ID.KOVAN_TESTNET]: 'Kovan Testnet',
  [AUC_CHAIN_ID.OPTIMISTIC_MAINNET]: 'Optimistic Ethereum Mainnet',
  [AUC_CHAIN_ID.OPTIMISTIC_TESTNET]: 'Optimistic Ethereum Kovan Testnet',
  [AUC_CHAIN_ID.POLYGON_MAINNET]: 'Polygon Mainnet',
  [AUC_CHAIN_ID.POLYGON_TESTNET]: 'Mumbai Testnet',
  [AUC_CHAIN_ID.RINKEBY_TESTNET]: 'Rinkeby Testnet',
  [AUC_CHAIN_ID.SHIDEN_MAINNET]: 'Shiden Network Mainnet',
  [AUC_CHAIN_ID.SHIDEN_TESTNET]: 'Shibuya Testnet',
  [AUC_CHAIN_ID.THETA_MAINNET]: 'Theta Mainnet',
  [AUC_CHAIN_ID.THETA_TESTNET]: 'Theta Testnet',
};
