export enum ROUTER_LINKS {
  CONNECT_WALLET = 'connect-wallet',
  ACCOUNT_BALANCE = 'account-balance',
  ACCOUNT_BUTTON = 'account-button',
  TRANSACTION_HISTORY = 'transaction-history',
  ALERT = 'alert',
  AVATAR = 'avatar',
  BUTTON = 'button',
  INPUT = 'input',
  TABLE = 'table',
  DIALOG = 'dialog',
  NETWORK_DROPDOWN = 'network-dropdown',
  DROPDOWN = 'dropdown',
  COPY_TO_CLIPBOARD = 'copy-to-clipboard',
  ICON = 'icon',
  PROGRESS_BAR = 'progress-bar',
  SPINNER = 'spinner',
  RIPPLE = 'ripple',
  SHORT_ADDRESS = 'short-address',
  GETTING_STARTED = 'getting-started',
  FAUCET = 'faucet',
}
