import { DIALOG_POSITIONS } from "../enums";

export type DialogPosition = DIALOG_POSITIONS.BOTTOM
  | DIALOG_POSITIONS.LEFT
  | DIALOG_POSITIONS.RIGHT
  | DIALOG_POSITIONS.TOP
  | DIALOG_POSITIONS.TOP_LEFT
  | DIALOG_POSITIONS.TOP_RIGHT
  | DIALOG_POSITIONS.BOTTOM_LEFT
  | DIALOG_POSITIONS.BOTTOM_RIGHT;
