import { APPLICATURE_DIALOG_POSITIONS } from "../enums";

export type ApplicatureDialogPosition = APPLICATURE_DIALOG_POSITIONS.BOTTOM
  | APPLICATURE_DIALOG_POSITIONS.LEFT
  | APPLICATURE_DIALOG_POSITIONS.RIGHT
  | APPLICATURE_DIALOG_POSITIONS.TOP
  | APPLICATURE_DIALOG_POSITIONS.TOP_LEFT
  | APPLICATURE_DIALOG_POSITIONS.TOP_RIGHT
  | APPLICATURE_DIALOG_POSITIONS.BOTTOM_LEFT
  | APPLICATURE_DIALOG_POSITIONS.BOTTOM_RIGHT;
