import { W3S_DIALOG_POSITIONS } from '../enums';
import { W3sEnumsTypeTransformer } from '../../types';

export type W3sDialogPosition = W3sEnumsTypeTransformer<W3S_DIALOG_POSITIONS.BOTTOM
  | W3S_DIALOG_POSITIONS.CENTER
  | W3S_DIALOG_POSITIONS.LEFT
  | W3S_DIALOG_POSITIONS.RIGHT
  | W3S_DIALOG_POSITIONS.TOP
  | W3S_DIALOG_POSITIONS.TOP_LEFT
  | W3S_DIALOG_POSITIONS.TOP_RIGHT
  | W3S_DIALOG_POSITIONS.BOTTOM_LEFT
  | W3S_DIALOG_POSITIONS.BOTTOM_RIGHT>;
