import { AUC_DIALOG_POSITIONS } from '../enums';
import { EnumsTypeTransformer } from '../../types';

export type AucDialogPosition = EnumsTypeTransformer<AUC_DIALOG_POSITIONS.BOTTOM
  | AUC_DIALOG_POSITIONS.CENTER
  | AUC_DIALOG_POSITIONS.LEFT
  | AUC_DIALOG_POSITIONS.RIGHT
  | AUC_DIALOG_POSITIONS.TOP
  | AUC_DIALOG_POSITIONS.TOP_LEFT
  | AUC_DIALOG_POSITIONS.TOP_RIGHT
  | AUC_DIALOG_POSITIONS.BOTTOM_LEFT
  | AUC_DIALOG_POSITIONS.BOTTOM_RIGHT>;
